# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Item.create(name: "氷結")
Item.create(name: "ハンドスピナー")
Item.create(name: "ビックル")
10.times do |i|
	Item.create(name: "ハーゲンダッツ #{i}味")
end
# id:1-13

10.times do |j|
	Shop.create(name: 'shop#{j}', lat: "#{j*1.2}", lng: "#{j*2}")
}
# id:1-10

ItemShop.create(item_id:1 , shop_id:1 , stock: 0)
ItemShop.create(item_id:1 , shop_id:3 , stock: 1)
ItemShop.create(item_id:1 , shop_id:4 , stock: 2)
ItemShop.create(item_id:1 , shop_id:5 , stock: 0)
ItemShop.create(item_id:1 , shop_id:7 , stock: 2)
ItemShop.create(item_id:1 , shop_id:9 , stock: 1)
ItemShop.create(item_id:1 , shop_id:10 , stock: 2)
ItemShop.create(item_id:2 , shop_id:1 , stock: 0)
ItemShop.create(item_id:2 , shop_id:6 , stock: 1)
ItemShop.create(item_id:3 , shop_id:1 , stock: 1)
ItemShop.create(item_id:3 , shop_id:2 , stock: 0)
ItemShop.create(item_id:3 , shop_id:3 , stock: 2)
ItemShop.create(item_id:3 , shop_id:6 , stock: 2)
ItemShop.create(item_id:3 , shop_id:9 , stock: 0)
ItemShop.create(item_id:3 , shop_id:10 , stock: 0)
ItemShop.create(item_id:4 , shop_id:1 , stock: 1)
ItemShop.create(item_id:4 , shop_id:4 , stock: 0)
ItemShop.create(item_id:4 , shop_id:8 , stock: 0)
ItemShop.create(item_id:5 , shop_id:1 , stock: 0)
ItemShop.create(item_id:5 , shop_id:2 , stock: 0)
ItemShop.create(item_id:5 , shop_id:5 , stock: 0)
ItemShop.create(item_id:6 , shop_id:1 , stock: 0)
ItemShop.create(item_id:6 , shop_id:4 , stock: 0)
ItemShop.create(item_id:6 , shop_id:5 , stock: 0)
ItemShop.create(item_id:6 , shop_id:7 , stock: 0)
ItemShop.create(item_id:6 , shop_id:8 , stock: 0)
ItemShop.create(item_id:6 , shop_id:10 , stock: 0)
ItemShop.create(item_id:7 , shop_id:1 , stock: 0)
ItemShop.create(item_id:7 , shop_id:7 , stock: 0)
ItemShop.create(item_id:8 , shop_id:1 , stock: 0)
ItemShop.create(item_id:8 , shop_id:2 , stock: 0)
ItemShop.create(item_id:8 , shop_id:5 , stock: 0)
ItemShop.create(item_id:8 , shop_id:6 , stock: 0)
ItemShop.create(item_id:8 , shop_id:7 , stock: 0)
ItemShop.create(item_id:8 , shop_id:8 , stock: 0)
ItemShop.create(item_id:8 , shop_id:9 , stock: 0)
ItemShop.create(item_id:8 , shop_id:10 , stock: 0)
ItemShop.create(item_id:9 , shop_id:1 , stock: 0)
ItemShop.create(item_id:9 , shop_id:2 , stock: 0)
ItemShop.create(item_id:9 , shop_id:3 , stock: 0)
ItemShop.create(item_id:9 , shop_id:4 , stock: 0)
ItemShop.create(item_id:9 , shop_id:5 , stock: 0)
ItemShop.create(item_id:9 , shop_id:6 , stock: 0)
ItemShop.create(item_id:9 , shop_id:7 , stock: 0)
ItemShop.create(item_id:9 , shop_id:8 , stock: 0)
ItemShop.create(item_id:9 , shop_id:9 , stock: 0)
ItemShop.create(item_id:9 , shop_id:10 , stock: 0)
ItemShop.create(item_id:10 , shop_id:1 , stock: 0)
ItemShop.create(item_id:11 , shop_id:1 , stock: 0)
ItemShop.create(item_id:11 , shop_id:10 , stock: 0)
ItemShop.create(item_id:12 , shop_id:1 , stock: 0)
ItemShop.create(item_id:12 , shop_id:5 , stock: 0)
ItemShop.create(item_id:12 , shop_id:6 , stock: 0)
ItemShop.create(item_id:12 , shop_id:10 , stock: 0)
ItemShop.create(item_id:13 , shop_id:1 , stock: 0)
ItemShop.create(item_id:13 , shop_id:2 , stock: 0)